Call you
Kalugaa/LifeIsGood pull request #13
Opened 2023-07-09 19:16 UTC by tanchikd

end we will call you section

2023-07-10 12:09 UTC, Kalugaa commented on src/css/sections/we-will-call-you.css
> +  letter-spacing: -0.96px;
Вкажи будь ласка letter-spacing в em

2023-07-10 12:10 UTC, Kalugaa commented on src/css/sections/we-will-call-you.css
> +  color: var(--black-color);
Передивись код на живій сторінці щоб видалити дублюючійся код (колір, фонт фемелі і т.д).

2023-07-10 12:16 UTC, Kalugaa commented on src/css/sections/we-will-call-you.css
> +.we-will-call-input {
Не знайшов стилізацію плейсхолдера.

2023-07-10 12:24 UTC, Kalugaa commented on src/css/sections/we-will-call-you.css
> +  .we-will-call-subtitle {
передивись макет, щось з текстом не так, можлово відсутні деякі стилі.

2023-07-10 12:29 UTC, Kalugaa requested changes
Зміни значення letter-spacing на em, подивись дублюючийся код, перевірь стилі. і застилізуй плейсхолдер

2023-07-10 19:05 UTC, tanchikd commented on src/css/sections/we-will-call-you.css
> +.we-will-call-input {
додано

2023-07-10 19:08 UTC, tanchikd commented on src/css/sections/we-will-call-you.css
> +  letter-spacing: -0.96px;
чому використовувати тут em? не розумію, бо все в пікселях йде, не преведено все до єдиної величини @Kalugaa

2023-07-10 19:35 UTC, tanchikd commented on src/css/sections/we-will-call-you.css
> +  .we-will-call-subtitle {
невірний font-family в body, має бути "font-family: 'DM Sans Regular';"

2023-07-10 19:54 UTC, tanchikd commented on src/css/sections/we-will-call-you.css
> +  color: var(--black-color);
переглянуто, видалено

2023-07-11 15:25 UTC, Kalugaa approved these changes

2023-07-11 15:25 UTC, merged