origin/footer
Kalugaa/LifeIsGood pull request #14
Opened 2023-07-10 08:55 UTC by Kostyantin-spec

footer

2023-07-10 11:17 UTC, Kalugaa commented on src/css/footer.css
> +    margin-bottom: 20px;
Прибери будь ласка цей маржин і постав геп на контейнер footer-div-logo.

2023-07-10 11:17 UTC, Kalugaa commented on src/css/footer.css
> +    padding-bottom: 40px;
Заміни будь ласка відступ вниз на маржин.

2023-07-10 11:22 UTC, Kalugaa commented on src/partials/footer.html
> +              <svg class="footer-svg-logo" width="16" height="16">
бачу свг не хоче міняти кольор, додам сьогодні чорну.

2023-07-10 11:25 UTC, Kalugaa commented on src/css/footer.css
> +    letter-spacing: -0.56px;
Переведіть будь ласка letter-spacing в em.

https://nekocalc.com/px-to-em-converter

2023-07-10 11:26 UTC, Kalugaa commented on src/css/footer.css
> +    letter-spacing: -0.56px;
Тут теж треба перевести.

2023-07-10 11:32 UTC, Kalugaa commented on src/css/footer.css
> +    padding-bottom: 40px;
Мені здається тут має бути маржин, а не падінг.

2023-07-10 12:03 UTC, Kalugaa requested changes
Переглянь будь ласка марджини і падінги, бо в деяких місцях плутаєш. Якщо уживаєш флекси то відступи між елементами краще виставляти гепом.

2023-07-10 12:20 UTC, Kalugaa commented
Для переносу тексту на іншу строку (там де адреса) можеш використати тег <br>. Ментор дозволив.

2023-07-11 09:03 UTC, Kostyantin-spec commented on src/css/footer.css
> +    margin-bottom: 20px;
+

2023-07-11 09:03 UTC, Kostyantin-spec commented on src/css/footer.css
> +    padding-bottom: 40px;
+

2023-07-11 09:04 UTC, Kostyantin-spec commented on src/css/footer.css
> +    letter-spacing: -0.56px;
+

2023-07-11 09:04 UTC, Kostyantin-spec commented on src/css/footer.css
> +    letter-spacing: -0.56px;
+

2023-07-11 09:04 UTC, Kostyantin-spec commented on src/css/footer.css
> +    padding-bottom: 40px;
+

2023-07-11 14:53 UTC, merged